### ISSUE TITLE
Rule of player's username

### ISSUE THREAD

**Issue by RainrainWu** [ccns/quiz-server#2]
## Currently
- A new player should be created via a POST request from chatbot poller of each platform.
- The database table only has a unique column `name` for each player.
- Will respond with status code 409 while the player's name conflict.

## Proposal
- Another non-unique column `nickname` for display.

**Comment by GHolk** [comment]
how about the naming convention?

* `$plotform/$username` 
* `$platform-$username`
* `$username@$platform`

**Comment by RainrainWu** [comment]
@GHolk  `$platform-$username` is preferred.
